# Generated by Django 5.2.6 on 2025-09-14 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applivros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='capa_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='livro',
            name='autor',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='livro',
            name='titulo',
            field=models.CharField(max_length=200),
        ),
    ]
